In [7]:
import numpy as np


In [21]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [19]:
x=[1,2,3,4,5]
print(x)
print(type(x))


[1, 2, 3, 4, 5]
<class 'list'>


In [15]:
l=[]
for i in range(1,5):
    int_l=int(input("Enter the number in array"))
    l.append(int_l)
print(int_l)    

Enter the number in array 6
Enter the number in array 6
Enter the number in array 2
Enter the number in array 3


3


In [ ]:
#Dimensions in Array
#1-D Array
#2-D Array
#3-D Array
# Higher Dimensional Array




In [27]:
ar2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4 5]
 [1 2 3 4 5]]
2


In [ ]:
ar3=np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])
print(ar3)
print(ar3.ndim)

In [39]:
arn=np.array([1,2,3,4,5],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10


In [ ]:
#Array filled with 0's
#Array filled with 1's
#Create an empty array
#An array with a range of elements
#Array diagonal element filled with 1's
#Create an array with values that are spaced linearly in a specified interval

In [15]:
ar_zero=np.zeros(4)
ar_zero1=np.zeros((3,4))
print(ar_zero)

print(ar_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
ar_one=np.ones(4)
ar_one1= np.ones((3,4))
print(ar_one)

print(ar_one1)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [57]:
ar_em=np.empty(4)
print(ar_em)

[ 5. 10. 15. 20.]


In [41]:
ar_rn=np.arange(11)
print(ar_rn)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [45]:
ar_dia=np.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [47]:
ar_dia=np.eye(4,6)
print(ar_dia)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [55]:
ar_lin =np.linspace(0,20,num=5)
print(ar_lin)                     

[ 0.  5. 10. 15. 20.]


In [ ]:
#Create NumPy Arrays with Random Numbers [rand(),randn(),ranf(),randint()]

In [59]:
var = np.random.rand(4)
print(var)

[0.37629206 0.19518587 0.96955035 0.56099829]


In [61]:
var1=np.random.rand(2,5)
print(var1)

[[0.86225323 0.38926511 0.94271162 0.82003985 0.55464352]
 [0.15156632 0.13581261 0.95087844 0.03831363 0.96357184]]


In [63]:
var2=np.random.randn(5)
print(var2)

[-0.2595251  -0.35756315  0.42690702  1.56943576  0.20525143]


In [67]:
var3=np.random.ranf(4)
print(var3)

[0.74293015 0.40740087 0.48020182 0.29448192]


In [73]:
var4=np.random.randint(5,20,5)
print(var4)

[ 9 11 19 17  7]


In [ ]:
#Data Types in NumPy Arrays
#bool(True or False)

In [85]:
var=np.array([2,3,5])
print("Data Type: ",var.dtype)

Data Type:  int64


In [87]:
var=np.array([2.4,3.9,5.3])
print("Data Type: ",var.dtype)

Data Type:  float64


In [91]:
var=np.array(["A","B","C",1,2,3,4,5])
print("Data Type: ",var.dtype)

Data Type:  <U21


In [95]:
var=np.array([2,3,5],dtype=np.int32)
print("Data Type: ",var.dtype)

Data Type:  int32


In [99]:
var=np.array([2,3,5],dtype= "f")
print("Data Type: ",var.dtype)

Data Type:  float32


In [107]:
var2=np.array([2,3,5])
new=np.float32(var2)

print("Data Type: ",var2.dtype)
print("Data Type: ",new.dtype)

print(var2)
print(new)

Data Type:  int64
Data Type:  float32
[2 3 5]
[2. 3. 5.]


In [109]:
var=np.array([2,3,5])
new_1 = var.astype(float)
print(var)

[2 3 5]


In [ ]:
#Shape & Reshaping in NumPy Arrays 

In [113]:
var=np.array([[1,2,3],[1,2,4]])
print(var)
print()
print(var.shape)

[[1 2 3]
 [1 2 4]]

(2, 3)


In [121]:
var1=np.array([1,2,3,4],ndmin=4)
print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


In [127]:
#Reshape
var2=np.array([1,2,3,4,5,6,1,2,3])
print(var2)
print(var2.ndim)
print()
x=var2.reshape(3,3)
print(x)

[1 2 3 4 5 6 1 2 3]
1

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [133]:
var3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()
x1=var3.reshape(2,3,2)
print(x1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [135]:
var3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()
x1=var3.reshape(2,3,2)
print(x1)
print(x1.ndim)

print()

one=x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [ ]:
#Arithmetic Operation in NumPy Array
#a+b    np.add(a,b)
#a-b    np.subtract(a,b)
#a*b    np.multiply(a,b)
#a/b    np.divide(a,b)
#a%b    np.mod(a,b)
#a**b    np.power(a,b)
#1/a    np.reciprocal(a)

In [137]:
var=np.array([1,2,3,4])
varadd=var+3
print(varadd)

[4 5 6 7]


In [143]:
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
varadd=var1+var2
print(varadd)

[2 4 6 8]


In [153]:
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
varadd=np.add(var1,var2)
print(varadd)

[2 4 6 8]


In [145]:
var=np.array([1,2,3,4])
varsub=var-3
print(varsub)

[-2 -1  0  1]


In [159]:
var=np.array([1,2,3,4])
varsub=np.subtract(var,3)
print(varsub)

[-2 -1  0  1]


In [161]:
var=np.array([1,2,3,4])
varmul=np.multiply(var,3)
print(varmul)

[ 3  6  9 12]


In [149]:
var=np.array([10,12,13,14])
varadd=var/2
print(varadd)

[5.  6.  6.5 7. ]


In [163]:
var=np.array([10,12,13,14])
vardiv=np.divide(var,2)
print(vardiv)

[5.  6.  6.5 7. ]


In [151]:
var=np.array([10,27,30,45])
varmod=var%3
print(varmod)

[1 0 0 0]


In [167]:
var=np.array([10,27,30,45])
varmod=np.mod(var,3)
print(varmod)

[1 0 0 0]


In [169]:
var=np.array([10,27,30,45])
varpow=np.power(var,3)
print(varpow)

[ 1000 19683 27000 91125]


In [179]:
var=np.array([10,27,30,45])
varpow=np.reciprocal(var)
print(varpow)

[0 0 0 0]


In [ ]:
#2D array

In [175]:
var21=np.array([[10,27,30,45],[1,2,3,4]])
var22=np.array([[10,27,30,45],[1,2,3,4]])
print(var21)
print()
print(var22)
print()
varadd2=var21*var22
print(varadd2)

[[10 27 30 45]
 [ 1  2  3  4]]

[[10 27 30 45]
 [ 1  2  3  4]]

[[ 100  729  900 2025]
 [   1    4    9   16]]


In [ ]:
#Arithmetic Functions
#np.min(x)
#np.max(x)
#np.argmin(x)
#np.sqrt(x)
#np.sin(x)
#np.cos(x)
#np.cumsum(x)

In [29]:
var=np.array([34,65,2,13,55,77,76,45])
print("min : ",np.min(var),np.argmin (var))
print("max : ",np.max(var),np.argmax (var))
print("Sqrt",np.sqrt(var))

min :  2 2
max :  77 5
Sqrt [5.83095189 8.06225775 1.41421356 3.60555128 7.41619849 8.77496439
 8.71779789 6.70820393]


In [27]:
var1=np.array([[1,2,3,4],[1,2,35,6]])
print(np.min(var1,axis=0)) #colum

var1=np.array([[5,2,3,4],[1,2,35,6]])
print(np.min(var1,axis=1)) #Row

[1 2 3 4]
[2 1]
Sqrt [[2.23606798 1.41421356 1.73205081 2.        ]
 [1.         1.41421356 5.91607978 2.44948974]]


In [35]:
var=np.array([2,3,4,5,6])
print("sin",np.sin(var))
print("cos",np.cos(var))
print("comsum",np.cumsum(var))

sin [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
cos [-0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
comsum [ 2  5  9 14 20]


In [19]:
import numpy as np
list=[1,2,3,4,5]
my_array=np.array(list)
print(my_array)
print("first element",my_array[0])
print("last element",my_array[-1])
print("my array after multiplay by 2:= ",my_array *2)

[1 2 3 4 5]
first element 1
last element 5
my array after multiplay by 2:=  [ 2  4  6  8 10]


In [45]:
#Broadcasting NumPy Arrays
x=np.array([1,2,3])
print(x.shape) # 3
print()
print(x)                     

y=np.array([[1],[2],[3]])
print(x.shape)
print()       
print(y)                 
print(x+y)

(3,)

[1 2 3]
(3,)

[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [67]:
x1=np.array([[1],[2]])
print(x1.shape)
print(x1)
print()

y1=np.array([[1,2,3],[1,2,3]])
print(y1.shape)
print(y1)
print()

print(x1+y1)

(2, 1)
[[1]
 [2]]

(2, 3)
[[1 2 3]
 [1 2 3]]

[[2 3 4]
 [3 4 5]]


In [73]:
#Indexing & slicing in NumPy Array
var1=np.array([1,2,3,4])
              #0,1,2,3
              #-4,-3,-2,-1
print(var[0])
print(var[-1])
print(var.ndim)

2
6
1


In [94]:
var=np.array([[2,3,5,6,9],[1,2,4,7,8]])
print(var2.ndim)
print(var2)
print(var2[0,2])
print(var2[1,-2])

2
[[4 5 6 4]
 [4 6 8 9]]
6
8


In [120]:
var3=np.array([[[2,3,5],[5,6,7]]])
print(var3.ndim)
print(var3)
print(var3[0,1,2])



3
[[[2 3 5]
  [5 6 7]]]
7


In [150]:
#Slicing NumPy Arrays 1D ndim
x=np.array([6,5,4,7,9,8])
          # 0,1,2,3,4,5
print(x)
print("2 to 4",x[1:4]) #start:stop
print("2 to End",x[1:]) 
print("start to 5",x[:5])
print("stop :",x[::2]) #step
print("stop :",x[1:5:2]) #start:stop:step


[6 5 4 7 9 8]
2 to 4 [5 4 7]
2 to End [5 4 7 9 8]
start to 5 [6 5 4 7 9]
stop : [6 4 9]
stop : [5 7]


In [160]:
#Slicing NumPy Arrays 2D ndim
y=np.array([[6,5,4,7,9,8],[1,3,5,6,7,8]]) #0,1
          # 0,1,2,3,4,5
print(y)
print("Dimenrion:",y.ndim)

print("5 to 9",y[0,1:5]) #start:stop
print("5 to End",y[1,2:]) 
print("start to 5",y[1,:5])
print("stop :",y[0,::2]) #step
print("stop :",y[1,1:5:2]) #start:stop:step

[[6 5 4 7 9 8]
 [1 3 5 6 7 8]]
Dimenrion: 2
5 to 9 [5 4 7 9]
5 to End [5 6 7 8]
start to 5 [1 3 5 6 7]
stop : [6 4 9]
stop : [3 6]


In [162]:
# Iterating NumPy Arrays
var=np.array([2,3,4,5,8,9,6])
print(var)
print()
for i in var:
    print(i)


[2 3 4 5 8 9 6]

2
3
4
5
8
9
6


In [172]:
var1=np.array([[2,4,6,3],[5,6,3,7]])
print(var1)
print()
for i in var1:
    for j in i:
        print(j)

[[2 4 6 3]
 [5 6 3 7]]

2
4
6
3
5
6
3
7


In [180]:
var2=np.array([[[2,4,6,3],[5,6,3,7]]])
print(var2)
print("Dimention D=",var2.ndim)
print()
for i in var2:
    for j in i:
        for k in j:  
            print(k)

[[[2 4 6 3]
  [5 6 3 7]]]
Dimention D= 3

2
4
6
3
5
6
3
7


In [184]:
var2=np.array([[[2,4,6,3],[5,6,3,7]]])
print(var2)
print("Dimention D=",var2.ndim)
print()
for i in np.nditer(var2):
    print(i)


[[[2 4 6 3]
  [5 6 3 7]]]
Dimention D= 3

2
4
6
3
5
6
3
7


In [186]:
var3=np.array([[[2,4,6,3],[5,6,3,7]]])
print(var3)
print("Dimention D=",var3.ndim)
print()
for i,d in np.ndenumerate(var3):
    print(i,d)

[[[2 4 6 3]
  [5 6 3 7]]]
Dimention D= 3

(0, 0, 0) 2
(0, 0, 1) 4
(0, 0, 2) 6
(0, 0, 3) 3
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 3
(0, 1, 3) 7


In [204]:
 #Copy vs View in NumPy Arrays
x=np.array([1,2,3,4,5,6])
co=x.copy()
x[3]=30
print("Orignal:=",x)
print("Copy:=",co)

Orignal:= [ 1  2  3 30  5  6]
Copy:= [1 2 3 4 5 6]


In [206]:
y=np.array([1,2,3,4,5,6])
vw=y.view()
vw[3]=30
print("Orignal:=",y)
print("view :=",vw)

Orignal:= [ 1  2  3 30  5  6]
view := [ 1  2  3 30  5  6]


In [3]:
#Join & split Functions NumPy Arrays
#join Array
import numpy as np
var=np.array([1,2,3,4,5])
var1=np.array([6,7,8,9,10])
new_var=np.concatenate((var,var1))
print(new_var)

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
vr=np.array([[1,2,3],[4,5,6]])
vr1=np.array([[6,7,8],[9,10,8]])
print(vr)
print()
print(vr1)
print()
#new_var=np.concatenate((vr,vr1),axis=1)
new_var=np.concatenate((vr,vr1),axis=0)
print(new_var)

[[1 2 3]
 [4 5 6]]

[[ 6  7  8]
 [ 9 10  8]]

[[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10  8]]


In [31]:
var_1=np.array([1,2,3,4,5])
var_2=np.array([6,7,8,9,10])
#n_var=np.stack((var_1,var_2),axis=1)
n_var=np.stack((var_1,var_2),axis=0)
n_var1=np.hstack((var_1,var_2)) #row
n_var2=np.vstack((var_1,var_2)) #columns
n_var3=np.dstack((var_1,var_2)) #height
print(n_var)
print()
print(n_var1)
print()
print(n_var2)
print()
print(n_var3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[ 1  2  3  4  5  6  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


In [47]:
#Split array
var=np.array([1,2,3,4,5,6,7,8,9])

print(var)

ar=np.array_split(var,3)
print()
print(ar)
print(type(ar))
print(ar[2])

[1 2 3 4 5 6 7 8 9]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
<class 'list'>
[7 8 9]


In [55]:
var1=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(var1)

ar1=np.array_split(var1,3)
ar2=np.array_split(var1,3,axis=1)
print()
print(ar1)
print()
print(ar2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [61]:
#Search,Sort,SearchShorted,Filter Functions
var=np.array([4,6,21,3,2,7,8,4,24,6])
            # 0,1,2,3,4,5,6,7,8,9,10
x=np.where(var%3==0)
print(x)

(array([1, 2, 3, 8, 9]),)


In [67]:
var1=np.array([1,2,3,4,8,9])
            
#x1=np.searchsorted(var1,6)
x1=np.searchsorted(var1,[5,6,7])
#x1=np.searchsorted(var1,6,side="right")
print(x1)

[4 4 4]


In [85]:
var_1=np.array([4,6,21,3,2,7,8,10,24,16])
var_3=np.array([[4,6,21],[3,2,7],[8,10,24]])
print(np.sort(var_1))
print()
print(np.sort(var_3))
var_2=np.array(["c","d","a","n","s"])
print(np.sort(var_2))

[ 2  3  4  6  7  8 10 16 21 24]

[[ 4  6 21]
 [ 2  3  7]
 [ 8 10 24]]
['a' 'c' 'd' 'n' 's']


In [89]:
#Filter Array
var_4=np.array([1,3,5,7,8])
f=[True,False,True,False,True]
new_a=var_4[f]
print(new_a)
print(type(new_a))

[1 5 8]
<class 'numpy.ndarray'>


In [ ]:
#NumPy Arrays Functions
#Arithmetic Function
#Shuffle
#Unique
#Resize
#Flatten
#Ravel

In [93]:
#shuffer
var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[3 2 1 5 4]


In [101]:
#unique
var1 = np.array([1,2,3,3,4,6,5,1,2,4,5])
x=np.unique(var1,return_index=True,return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 4, 6, 5]), array([2, 2, 2, 2, 2, 1]))


In [115]:
#resize
var2=np.array([1,2,3,4,5,6,7,8,9])
y=np.resize(var2,(4,2))
print(y)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [125]:
#flatten Order:{'C','F','A','K'}
var2=np.array([1,2,3,4,5,6,7,8,9])
y=np.resize(var2,(4,2))
print(y)
print()
print("Flatten :",y.flatten(order="F"))
print("Ravel: ",np.ravel(y,order="A"))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Flatten : [1 3 5 7 2 4 6 8]
Ravel:  [1 2 3 4 5 6 7 8]


In [159]:
#Insert and Delete Function
var=np.array([1,2,3,4,5])
print(var)
#v=np.insert(var,5,6)
#v=np.insert(var,(2,5),6)
x=np.append(var,6)
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]


In [161]:
var1=np.array([[1,2,3],[4,5,6]])
#v1=np.insert(var1,2,7,axis=0)
#v1=np.insert(var1,2,7,axis=1)
#v1=np.insert(var1,2,[6,9,8],axis=0)
v1=np.append(var1,[[6,9,8]],axis=0)
print(v1)

[[1 2 3]
 [4 5 6]
 [6 9 8]]


In [ ]:
var2=np.array([1,2,3,4,5])
print(var)
y=np.delete(var,)

In [169]:
#Matrix in NumPyArray
var=np.matrix([[1,2,3],[4,5,6]])
print(var)
print(type(var))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [171]:
var1=np.array([[1,2,3],[4,5,6]])
print(var1)
print(type(var1))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [177]:
#Arithmetric Operation in Matrix
var1=np.array([[1,2,3],[4,5,6]])
var2=np.array([[1,2,3],[4,5,6]])
print(var1+var2)
print(var1-var2)
print(var1*var2)

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]


In [ ]:
#Matrix Function in NumPy Arrays
#Transpose
#Swapaxes
#Inverse
#Power
#Determinate

In [183]:
var=np.array([[1,2,3],[4,5,6]])
print(var)
print()
print(np.transpose(var))
print()
print(var.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [197]:
var1=np.matrix([[1,2],[4,5]])
print(var1)
print()
print(np.swapaxes(var1,0,1))

[[1 2]
 [4 5]]

[[1 4]
 [2 5]]


In [199]:
var2=np.matrix([[1,2],[4,5]])
print(var2)
print()
print(np.linalg.inv(var2))

[[1 2]
 [4 5]]

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [207]:
var3=np.matrix([[1,2],[4,5]])
print(var3)
print()
print(np.linalg.matrix_power(var3,2))
print(np.linalg.matrix_power(var3,0))
print(np.linalg.matrix_power(var3,-2))

[[1 2]
 [4 5]]

[[ 9 12]
 [24 33]]
[[1 0]
 [0 1]]
[[ 3.66666667 -1.33333333]
 [-2.66666667  1.        ]]


In [214]:
var4=np.matrix([[1,2],[4,5]])
print(var4)
print()
print(np.linalg.det(var4))

[[1 2]
 [4 5]]

-2.9999999999999996
